# Generated by Django 6.0.2 on 2026-02-08 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Mark whether the task has been completed'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Add additional details about your task (optional)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(error_messages={'blank': 'Task title cannot be blank. Please enter a title.', 'required': 'Task title is required. Please enter a title.'}, help_text='Enter a descriptive title for your task', max_length=200, validators=[django.core.validators.MinLengthValidator(1, message='Task title cannot be empty'), django.core.validators.MaxLengthValidator(200, message='Task title cannot exceed 200 characters')]),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_created_db4e37_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_completed'], name='tasks_is_comp_a2f0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='tasks_title_b13983_idx'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
